import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Import Rock Grotesk Bold from the app/fonts directory
const rockGrotesk = localFont({
  src: "./fonts/RocGrotesk.otf", // Path within the app directory
  variable: "--font-rock-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, orientation=portrait" />
        {/* Add any other meta tags you may need */}
      </head>
      <body
        className={`${rockGrotesk.variable} antialiased`}
        style={{ fontFamily: 'var(--font-rock-grotesk), sans-serif' }}
      >
        {children}
      </body>
    </html>
  );
}
